name: Heroboard

options:
  bundleIdPrefix: macos-heroboard
  createIntermediateGroups: true

packages:
  AppUpdater:
    url: https://github.com/alanhamlett/AppUpdater
    branch: master
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    exactVersion: 10.22.0

targets:
  Heroboard:
    type: application
    platform: macOS
    deploymentTarget: 10.15
    sources: [Heroboard]
    settings:
      CURRENT_PROJECT_VERSION: local-build
      MARKETING_VERSION: local-build
      INFOPLIST_FILE: Heroboard/Heroboard-Info.plist
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ${SV_DEVELOPMENT_TEAM}
      ENABLE_HARDENED_RUNTIME: YES
      DEAD_CODE_STRIPPING: YES
      SWIFT_OBJC_BRIDGING_HEADER: Heroboard/Heroboard-Bridging-Header.h
    postCompileScripts:
      - script: ./Scripts/Lint/swiftlint lint --quiet
        name: Swiftlint
    dependencies:
      - target: Heroboard Helper
      - package: AppUpdater
      - package: Firebase
        product: FirebaseCrashlytics
    postBuildScripts:
      - script: |
          LOGIN_ITEMS_DIR="$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/Library/LoginItems"
          rm -rf "$LOGIN_ITEMS_DIR"
          mkdir -p "$LOGIN_ITEMS_DIR"
          mv "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/Resources/Heroboard Helper.app" "$LOGIN_ITEMS_DIR/"
        name: Move "Heroboard Helper.app" to LoginItems
      - script: Scripts/Firebase/upload-dSYM.sh
        name: Firebase
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
  Heroboard Helper:
    type: application
    platform: macOS
    deploymentTarget: 10.15
    sources: [Heroboard Helper]
    settings:
      CURRENT_PROJECT_VERSION: local-build
      MARKETING_VERSION: local-build
      INFOPLIST_FILE: Heroboard Helper/Heroboard Helper-Info.plist
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ${SV_DEVELOPMENT_TEAM}
      ENABLE_HARDENED_RUNTIME: YES
      DEAD_CODE_STRIPPING: YES
      SKIP_INSTALL: YES
    postCompileScripts:
      - script: ./Scripts/Lint/swiftlint lint --quiet
        name: Swiftlint
